### ISSUE TITLE
LIMITED Features 

### ISSUE THREAD

**Issue by WeakLinkss** [swagkarna/Rafel-Rat#118]
Most of features don't work,

Working Commands:
1. change wallpaper
2. send sms using target phone
3. lock screen
4. toast info on screen

THANK YOU

**Comment by Bannana12345** [comment]
just follow the instructions

**Comment by 192425** [comment]
> 大多数功能不起作用，
> 
> 工作命令：
> 
> 1. 更换壁纸
> 2. 使用目标手机发送短信
> 3. 锁屏界面
> 4. 屏幕上的 Toast 信息
> 
> 谢谢

我反编译之后不能成功上线，链接正确，你有遇到过这种问题吗

**Comment by harshit9820** [comment]
Google Play Protect is not bypassing.. Google Play Protect block the application

**Comment by rotodarobull** [comment]
> Google Play Protect is not bypassing.. Google Play Protect block the application

same......
