### ISSUE TITLE
Raptor Page not working

### ISSUE THREAD

**Issue by Robob208** [swagkarna/Rafel-Rat#122]
**Devices are not showing in the list but i get the notification on discord that victim is connected
![Screenshot (9)](https://github.com/swagkarna/Rafel-Rat/assets/160517103/48e06b1d-3c8d-4f9b-8321-4d2b688a1ec8)
![Screenshot (8)](https://github.com/swagkarna/Rafel-Rat/assets/160517103/eedadcac-b107-4962-a0b7-a069532e61a4)
**

**Comment by AbolfazlDi** [comment]
Hello and thank you for your work.
I dont find MailConfig.smali in the story file

**Comment by Robob208** [comment]
> Hello and thank you for your work.
> I dont find MailConfig.smali in the story file 

I don't understand, I thought he said the video was old
