### ISSUE TITLE
constant toast notifications

### ISSUE THREAD

**Issue by gmoore2001** [swagkarna/Rafel-Rat#13]
Compiled app notifies my test victim of absolutely everything it does, needs a silent mode.
Spams toast bars over and over saying try and kill me ;) and battery %

**Comment by Arioshoma** [comment]
Solved?

**Comment by Shehzadcyber** [comment]
No sir ,, Please provide link for full Article.

Thank you sir,

**Comment by swagkarna** [comment]
> Solved?

@Arioshoma Hey man its not an bug nor issue if u know coding u will know why i include this code...Moreover this will not be removed from rafel if u can u can remove it
