### ISSUE TITLE
waited ...

### ISSUE THREAD

**Issue by graysuit** [swagkarna/Rafel-Rat#17]
I waited for 99th
and now its my turn,
congrats for 100th star !!!!!!!!!!!!!!

**Comment by graysuit** [comment]
by me. lol

**Comment by swagkarna** [comment]
@graysuit Wait for 299th for Defeat-Defender And star Again For 300th ...

Ok I Have an Important thing to share one thing ....Whenever You bind any payload with android app you will get these issue and there is no proper resource to solve this...Every Noobs Face this issue and they cant able to solve ...So share this with your friends whoever intrested in `androidPentesting`[Link]https://github.com/Malicious-Xv/Metasploit-Re-Build-Apk-Fail)

**Comment by graysuit** [comment]
Sure, will wait for 300th,400th,500th....
Binding apk looks interesting, so I shared link to my group.

Thanks so much.
