### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Chikimaro** [swagkarna/Rafel-Rat#18]
Thanks for the share, the only problem i found is while compiling the apk using APK Easy Tool.
![image](https://user-images.githubusercontent.com/49518807/118564075-2f673080-b75f-11eb-9aa6-1e5704bea19b.png)
the problems source come from the style.xml at Rafel-Rat-main\story\res\values-v28 
lines:
styles.xml:18
styles.xml:20
styles.xml:8
styles.xml:10
-----------------
Edit:

I just found out the problem, it is from the whole APK easy tool and not the decompiled apk, since i decompiled a fresh new IsntaStorySaver.apk v1.0.1 and recompiled it instantly but it failed ...

I guess the best solution to go with the first method

**Comment by swagkarna** [comment]
ok.. First Uninstall your apktool and download this Apktool v1.57 [Here](https://www.filecroco.com/download-apk-easy-tool/)
Now Turn off your windows defender real-time protection and download again the zip file from my github repo and compile again
