### ISSUE TITLE
 get sms log

### ISSUE THREAD

**Issue by andrescastro7036** [swagkarna/Rafel-Rat#19]
I can't get the sms log
![sms](https://user-images.githubusercontent.com/83835568/119178640-99b7f380-ba33-11eb-935e-b3d88d289d0f.PNG)

**Comment by swagkarna** [comment]
Click on Tower image and refresh the page and click Dosay...

**Comment by swagkarna** [comment]
Click on Tower image and refresh the page and click Dosay...

**Comment by andrescastro7036** [comment]
perfect , thanks
