### ISSUE TITLE
'java' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by m0nd4y99** [swagkarna/Rafel-Rat#6]
I use Apk Easy Tool V1.57. When starting the compile a problem occurred. The problem is showing in the log **('java' is not recognized as an internal or external command,
operable program or batch file)**. Is there any solution..?

**Comment by swagkarna** [comment]
I Think you are noob if you u will face many problems on setting up this rat ...Join this Discord server to ask all your questions 
https://discord.gg/AnW5KwTy
Java Download Link...
https://www.filehorse.com/download-java-runtime/
