### ISSUE TITLE
000webhost error

### ISSUE THREAD

**Issue by pretech86** [swagkarna/Rafel-Rat#7]
i put the server files on 000webhost but when i try to access to the login.php it said this page not found 

can you give some details about this steps

**Comment by pretech86** [comment]
it working but when i try to login i get the following 

Warning: Cannot modify header information - headers already sent by (output started at /storage/ssd1/655/16436655/public_html/login.php:9) in /storage/ssd1/655/16436655/public_html/login.php on line 11

**Comment by swagkarna** [comment]
k wati let me check

**Comment by pretech86** [comment]
also i get this error when i hit control panel


Warning: file_get_contents(../private/storage/device_list.json): failed to open stream: No such file or directory in /storage/ssd1/655/16436655/public_html/index.php on line 79

**Comment by swagkarna** [comment]
Just Remove this on login.php "echo $login_status;" Contact me on discord if you have not solved

**Comment by pretech86** [comment]
i can't find this ( "echo $login_status;" ) in login.php file

**Comment by swagkarna** [comment]
I HAVE UPDATED login.php file run remove it and add from my github profile github.com/rafel

**Comment by pretech86** [comment]
in this repo or another one ?

**Comment by graysuit** [comment]
> 
> 
> in this repo or another one ?

- Delete all files in **public_html**.
- Download this repo again. 
- Upload it
