### ISSUE TITLE
can't record  audio 

### ISSUE THREAD

**Issue by tinaayam** [swagkarna/Rafel-Rat#8]
Hi i  created  the apk using  apk easy tool.
the app installed  perfectly and i get the connection as well but there is no option of recording audio.
i clicked on Rehber but can't record audio.
how to fix this.
microphone access for the rat is granted.

**Comment by graysuit** [comment]
@tinaayam 
what android version you use ?
like `1-12`

**Comment by swagkarna** [comment]
> Hi i created the apk using apk easy tool.
> the app installed perfectly and i get the connection as well but there is no option of recording audio.
> i clicked on Rehber but can't record audio.
> how to fix this.
> microphone access for the rat is granted.

@tinaayam Recording Feature is not available

**Comment by tinaayam** [comment]
please include

**Comment by swagkarna** [comment]
@tinaayam still rafel is in beta stage use after it get completes
