### ISSUE TITLE
how tp bind with another apk

### ISSUE THREAD

**Issue by unfairDude** [swagkarna/Rafel-Rat#85]
hi, i reaaly appreciate yor job. but i dont understand how to make this work with another app and not just with blackmart.
Is there a way to bind rat with another apk? I tried decompiling spotify but there isnt raptor folder

**Comment by iamjamilkhan** [comment]
Same here i also want to bind it with my own app similar to Blackmart website

**Comment by iamjamilkhan** [comment]
Developer must attach a guide for it
