### ISSUE TITLE
Client side

### ISSUE THREAD

**Issue by Arioshoma** [swagkarna/Rafel-Rat#9]
Regarding step one:
```
Building Apk with ApkEasyTool:
1: Navigate to \NetflixMod\smali\com\velociraptor\raptor
```
Inside com folder there is no folder named velociraptor.
Can you put some more details about the steps or upload YT for it, please?

**Comment by graysuit** [comment]
@Arioshoma 
https://vimeo.com/527942173
https://vimeo.com/527959545

**Comment by swagkarna** [comment]
@Arioshoma Dont use this rat now its still in development

**Comment by Arioshoma** [comment]
@swagkarna Do know have any idea about when this will be available to use?

**Comment by swagkarna** [comment]
@Arioshoma till tomorrow night
