### ISSUE TITLE
Victim Files Download Issue...

### ISSUE THREAD

**Issue by igsfm** [swagkarna/Rafel-Rat#96]
In "Folder" Left Menu getting issue, "Download Files" button sends request with green toast but after that nothing happened... i mean files are not getting download.

![2022-10-18_191517](https://user-images.githubusercontent.com/60702905/196455797-f999ea58-68e0-4532-a109-39809d63d205.png)

**Comment by saiyed205** [comment]
Can't fetch sms

**Comment by igsfm** [comment]
> Can't fetch sms

![2022-10-23_071851](https://user-images.githubusercontent.com/60702905/197369962-dc69596b-1615-4b49-9b30-8e83ed70992d.png)
